name: rasqual
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - tabix
  - bcftools
  - vcftools
  - pandas
  - argparse
  - subprocess
  - scipy
  - fileinput
  - r-base=4.0.2
  - r-data.table